### ISSUE TITLE
[Bug] Merged deals don't get remove in final models

### ISSUE THREAD

**Issue by codingcyclist** [fivetran/dbt_hubspot#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

<img width="781" alt="image" src="https://github.com/fivetran/dbt_hubspot/assets/41942954/c0d51222-f804-4551-85e3-2e5a9e667eca">

- [expected] Merged **contacts** automatically get removed and collapsed into `calculated_merged_vids` in the final models (using the `CONTACT.property_hs_calculated_merged_vids` column)
- [expected] Merged **companies** can be manually filtered from final models, using the `is_deleted` column
- [unexpected] Merged deals don't get removed in final models and **can't be filtered**, which causes deals to still stick around even though they are "stale"

### Expected behavior

Adopt the same behavior as for contacts: merged deals should get removed in final models (using the `merged_deal` table) and the IDs of merged deals should get collapsed into a `calculated_merged_vids` column

### dbt Project configurations

```
Running with dbt=1.7.4
dbt version: 1.7.4
python version: 3.10.12
python path: /home/vscode/venv/bin/python
os info: Linux-5.15.49-linuxkit-aarch64-with-glibc2.31
Using profiles dir at /workspace/dbt
Using profiles.yml file at /workspace/dbt/profiles.yml
Using dbt_project.yml file at /workspace/dbt/dbt_project.yml
adapter type: snowflake
adapter version: 1.7.1
Configuration:
  profiles.yml file [OK found and valid]
  dbt_project.yml file [OK found and valid]
Required dependencies:
 - git [OK found]
```

### Package versions

```yaml
packages:
  - package: dbt-labs/dbt_external_tables
    version: "0.8.5"
  - package: fivetran/hubspot
    version: [">=0.15.0", "<0.16.0"]
  - package: dbt-labs/dbt_utils
    version: "1.1.1"
  - package: calogica/dbt_expectations
    version: [">=0.10.0", "<0.11.0"]
```

### What database are you using dbt with?

snowflake

### dbt Version

1.7.4

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.
