### ISSUE TITLE
[Bug] Duplicate field first_conversion_date in hubspot__contacts model

### ISSUE THREAD

**Issue by cmclaughlin829** [fivetran/dbt_hubspot#158]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the issue

In v0.23.0 the field `first_conversion_date` is added to `hubspot__contacts` via a new join with `int_hubspot__form_metrics__by_contact`. When the config `hubspot__pass_through_all_columns: true` exists it leads to the following error:
```
SQL compilation error:
  duplicate column name 'FIRST_CONVERSION_DATE'
  compiled Code at target/run/hubspot/models/marketing/hubspot__contacts.sql
```
This is because `first_conversion_date` is a property that is created by hubspot on the contact object and is passed through in `stg_hubspot__contact` via:
```
"PROPERTY_FIRST_CONVERSION_DATE" as first_conversion_date
```

### Relevant error log or model output

```shell
SQL compilation error:
  duplicate column name 'FIRST_CONVERSION_DATE'
  compiled Code at target/run/hubspot/models/marketing/hubspot__contacts.sql
```

### Expected behavior

Ability to run our dbt project with `hubspot__pass_through_all_columns:true` without receiving a duplicate column name error.

### Possible solution

We utilize many passthrough columns in our downstream models so we would like to avoid setting `hubspot__pass_through_all_columns: false` and forcing a manual list of passthrough columns and aliases. Ideally, the `first_conversion_date` field that is created within `int_hubspot__form_metrics__by_contact` would either be renamed, or removed if it is simply duplicating the hubspot property.

### dbt Project configurations

```
vars:
  # Hubspot package variables
  hubspot_database: raw
  hubspot_schema: hubspot
  hubspot_email_event_forward_enabled: false
  hubspot_email_event_print_enabled: false
  hubspot__pass_through_all_columns: true
  hubspot_contact_merge_audit_enabled: true 
  hubspot_contact_list_enabled: false
  hubspot_contact_list_member_enabled: false
```

### Package versions

```
packages:
  - package: dbt-labs/audit_helper
    version: [">=0.12.0","<0.13.0"]
  - package: dbt-labs/codegen
    version: [">=0.13.0", "<0.14.0"]
  - package: metaplane/dbt_expectations
    version: [">=0.10.0", "<0.11.0"]
  - package: dbt-labs/dbt_utils # Including directly to avoid relying on this being included in other packages
    version: [">=1.0.0", "<2.0.0"]
  - package: fivetran/hubspot
    version: [">=0.23.0", "<0.24.0"] 
  - package: fivetran/salesforce
    version: [">=1.2.0", "<1.3.0"]
  - package: fivetran/salesforce_formula_utils
    version: [">=0.10.0", "<0.11.0"]
  - package: get-select/dbt_snowflake_monitoring
    version: [">=5.0.0", "<6.0.0"]
  - package: snowplow/snowplow_web
    version: [">=0.14.0", "<0.15.0"]
```

### What database are you using dbt with?

snowflake

### How are you running this dbt package?

dbt Cloud™

### dbt Version

```
Core:
  - installed: 1.8.6 
  - latest:    1.10.2 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.8.3 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [x] Yes, but I will need assistance.
- [ ] No.
