### ISSUE TITLE
Models still created when `_enabled: false` is set

### ISSUE THREAD

**Issue by joshuataylor** [fivetran/dbt_hubspot#29]
Hi!

We have this in our `dbt_project.yml`:
```
vars:
  hubspot_source:
...
    hubspot_marketing_enabled: false                        # Disables all marketing models
    hubspot_email_event_enabled: false                      # Disables all email_event models and functionality
...
```

But these are still created.

**Comment by fivetran-kristin** [comment]
Hey @joshuataylor, apologies for the delayed response!

The problem here is that you need to update the variables for both the hubspot_source & hubspot packages, or define the variables as global.  So, for example:

```
vars:
  hubspot_source:
    hubspot_marketing_enabled: false
    hubspot_email_event_enabled: false
  hubspot:
    hubspot_marketing_enabled: false
    hubspot_email_event_enabled: false
```

OR

```
vars:
  hubspot_marketing_enabled: false
  hubspot_email_event_enabled: false
```
