### ISSUE TITLE
BUG - alias not working

### ISSUE THREAD

**Issue by khookguy** [fivetran/dbt_hubspot#45]
**Are you a current Fivetran customer?** 
Yes.
Mark Hansen
Consultant
Edcura

**Describe the bug**
alias fails to rename the hubspot__contact fields 'first_name' and ''last_name' to 'firstname' and 'lastname'

**Steps to reproduce**
1. Add the following code to dbt_project.yml
```
hubspot__contact_pass_through_columns:
    - name: "first_name"
      alias: "firstname"
    - name: "last_name"
      alias: "lastname"
```
2. Run `dbt -m hubspot --full-refresh`
3. Example the table `hubspot__contacts`
4. You will see the table has columns 'first_name' and 'last_name' rather than 'firstname' and 'lastname'

**Expected behavior**
The column 'first_name' should have become 'firstname' and the column 'last_name' should have become 'lastname'

**Project variables configuration**

```yml
name: 'hubspot'
version: '0.3.3'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.20.0"]

vars:
  hubspot:
    contact: "{{ ref('stg_hubspot__contact') }}"
    contact_list: "{{ ref('stg_hubspot__contact_list') }}"
    contact_list_member: "{{ ref('stg_hubspot__contact_list_member') }}"
    contact_property_history: "{{ ref('stg_hubspot__contact_property_history') }}"

    company: "{{ ref('stg_hubspot__company') }}"
    company_property_history: "{{ ref('stg_hubspot__company_property_history') }}"

    deal: "{{ ref('stg_hubspot__deal') }}"
    deal_stage: "{{ ref('stg_hubspot__deal_stage') }}"
    deal_company: "{{ ref('stg_hubspot__deal_company') }}"
    deal_pipeline: "{{ ref('stg_hubspot__deal_pipeline') }}"
    deal_pipeline_stage: "{{ ref('stg_hubspot__deal_pipeline_stage') }}"
    deal_property_history: "{{ ref('stg_hubspot__deal_property_history') }}"

    owner: "{{ ref('stg_hubspot__owner') }}"

    email_event_bounce: "{{ ref('stg_hubspot__email_event_bounce') }}"
    email_event_click: "{{ ref('stg_hubspot__email_event_click') }}"
    email_event_deferred: "{{ ref('stg_hubspot__email_event_deferred') }}"
    email_event_delivered: "{{ ref('stg_hubspot__email_event_delivered') }}"
    email_event_dropped: "{{ ref('stg_hubspot__email_event_dropped') }}"
    email_event_forward: "{{ ref('stg_hubspot__email_event_forward') }}"
    email_event_open: "{{ ref('stg_hubspot__email_event_open') }}"
    email_event_print: "{{ ref('stg_hubspot__email_event_print') }}"
    email_event_sent: "{{ ref('stg_hubspot__email_event_sent') }}"
    email_event_spam_report: "{{ ref('stg_hubspot__email_event_spam_report') }}"
    email_event_status_change: "{{ ref('stg_hubspot__email_event_status_change') }}"
    email_event: "{{ ref('stg_hubspot__email_event') }}"

    engagement: "{{ ref('stg_hubspot__engagement') }}"
    engagement_call: "{{ ref('stg_hubspot__engagement_call') }}"
    engagement_company: "{{ ref('stg_hubspot__engagement_company') }}"
    engagement_contact: "{{ ref('stg_hubspot__engagement_contact') }}"
    engagement_deal: "{{ ref('stg_hubspot__engagement_deal') }}"
    engagement_email_cc: "{{ ref('stg_hubspot__engagement_email_cc') }}"
    engagement_email_to: "{{ ref('stg_hubspot__engagement_email_to') }}"
    engagement_email: "{{ ref('stg_hubspot__engagement_email') }}"
    engagement_meeting: "{{ ref('stg_hubspot__engagement_meeting') }}"
    engagement_note: "{{ ref('stg_hubspot__engagement_note') }}"
    engagement_task: "{{ ref('stg_hubspot__engagement_task') }}"

    email_metrics: [
                    'bounces',
                    'clicks',
                    'deferrals',
                    'deliveries',
                    'drops',
                    'forwards',
                    'opens',
                    'prints',
                    'spam_reports',
                    'unsubscribes'
                    ]
  hubspot__contact_pass_through_columns:
    - name: "first_name"
      alias: "firstname"
    - name: "last_name"
      alias: "lastname"


models:
  hubspot:
    +materialized: table
    +schema: hubspot
    marketing:
      intermediate:
        +materialized: ephemeral
    sales:
      intermediate:
        +materialized: ephemeral
```

**Package Version**

```yml
packages:
  - package: fivetran/hubspot_source
    version: [">=0.3.0", "<0.4.0"]
```

**Warehouse**
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**
<img width="747" alt="2021-06-21_15-26-12" src="https://user-images.githubusercontent.com/1290827/122816698-12190b00-d2a5-11eb-81a3-4902159b9165.png">

**Please indicate the level of urgency** 
Urgent. Dashboarding is broken since upgrading to latest version of fivetran/hubspot_source

**Are you interested in contributing to this package?** 
- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
