### ISSUE TITLE
BUG - hubspot_engagment_task CASTING error

### ISSUE THREAD

**Issue by brettkobo** [fivetran/dbt_hubspot#53]
**Are you a current Fivetran customer?** 
Hello name name is Brett Kobold and I am currently a customer of Fivetran under the account Retina.AI

**Describe the bug**
When I run the models, I get an error for the **hubspot_engagment_table**. I have pasted the error below. I am not sure what coloum is failing to CAST and I believe I do not have custom properies on engagments.

```
Database Error in model stg_hubspot__engagement_task (models/stg_hubspot__engagement_task.sql)
  001065 (22023): SQL compilation error:
  Function TRY_CAST cannot be used with arguments of types TIMESTAMP_TZ(9) and TIMESTAMP_NTZ(9)
  compiled SQL at target/run/hubspot_source/models/stg_hubspot__engagement_task.sql

```
**Steps to reproduce**
Run FiveTran for hubspot tables, excluding any history tables to redunce number of calls.
Install the hubspot DBT package.
dbt_run on DBT cloud.
Get error that can't TRY_CAST timestamps.
Go check Snowflake to see if tables were created.

**Expected behavior**
I expected the engagement tasks table to be created, currently I do not see that in my Snowflake instance.

**Project variables configuration**

```yml

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'retina_rev_ana'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  retina_rev_ana:
      # Applies to all files under models/example/
      example:
          materialized: view

vars:
  hubspot_source:
    hubspot_database: PC_FIVETRAN_DB
    hubspot_schema: HUBSPOT
    hubspot__pass_through_all_columns: true
    hubspot__email_event_forward_enabled: false
    hubspot__email_event_print_enabled: false
```

**Package Version**

```yml
packages:
  - package: fivetran/hubspot
    version: 0.4.1
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [ X] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**
![image](https://user-images.githubusercontent.com/8419147/129097207-1b0ff728-065e-4643-92ff-15bf5f87a963.png)

**Please indicate the level of urgency** 
This isn't critical but I would like to have all the tables built as I will be doing reporting on SDRs this week and their different engagements within Hubspot

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ X] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

I just started working with DBT but would be happy to help in the future on development. I know SQL.
