### ISSUE TITLE
BUG - Deal and deal stages data type join mismatch on Redshift

### ISSUE THREAD

**Issue by scotthibberd** [fivetran/dbt_hubspot#61]
**Are you a current Fivetran customer?** 
Yes. Scott Hibberd - Infogrid, BI Analyst

**Describe the bug**
Running `dbt run` returns an error for the `hubspot__deals` and `hubspot__deal_stages` models

The error I receive is `JOIN/USING types bigint and character varying cannot be matched`

**Steps to reproduce**
1. Import the Fivetran Hubspot package
2. Run `dbt run`

**Expected behavior**
Models should build without error

**Project variables configuration**

```yml
name: 'infogrid_bi'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:

  hubspot__pass_through_all_columns: true 

  hubspot_email_event_spam_report_enabled: false
  hubspot_email_event_print_enabled: false
  hubspot_email_event_forward_enabled: false
```

**Package Version**

```yml
  - package: fivetran/hubspot
    version: [">=0.5.0", "<0.6.0"]
```

**Warehouse**
- [ ] BigQuery
- [x] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
For both models, the build fails due to the join within the `deal_fields_joined` CTE

It fixes for me to rewrite the join as follow:

```
select 
        deals.*,
        pipelines.pipeline_label,
        pipelines.is_active as is_pipeline_active,
        pipeline_stages.pipeline_stage_label,
        owners.email_address as owner_email_address,
        owners.full_name as owner_full_name

    from deals
    left join pipelines on deals.deal_pipeline_id = cast(pipelines.deal_pipeline_id as bigint)
    left join pipeline_stages on deals.deal_pipeline_stage_id = cast(pipeline_stages.deal_pipeline_stage_id as bigint)
    left join owners on deals.owner_id = owners.owner_id

```

**Screenshots**

**Please indicate the level of urgency** 
Currently in the process of building Hubspot reporting - we can workaround temporarily by overwriting the package model files, but a longer term solution is preferable. 

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
