### ISSUE TITLE
Deal Pipeline Stage Label is duplicated

### ISSUE THREAD

**Issue by moseleyi** [fivetran/dbt_hubspot#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Here is an extract for a deal that has two different stages:

![image](https://user-images.githubusercontent.com/16131590/182124910-564b601e-3439-4137-926e-f55911d867cf.png)

The stage_ids are properly mapped in `stg_hubspot__deal_pipeline_stage`

But then, `hubspot__deal_stages` shows the same id for both stages 

![image](https://user-images.githubusercontent.com/16131590/182125055-89abe87d-d23a-4c12-9e99-6707352a655b.png)

### Expected behavior

The first row should have Pipeline_stage_label = New and Deal_pipeline_stage_id = 6309924

### dbt Project configurations

```
vars:
  hubspot_source:
    hubspot_database: FIVETRAN
    hubspot_schema: hubspot
  hubspot_email_event_print_enabled: false
  hubspot_email_event_forward_enabled: false
  hubspot_contact_merge_audit_enabled: true
  hubspot__pass_through_all_columns: true
```

### Package versions

packages:
  - package: dbt-labs/audit_helper
    version: 0.5.0
  - package: fivetran/hubspot
    version: [">=0.5.0", "<0.6.0"]

### What database are you using dbt with?

snowflake

### dbt Version

1.1.1

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
