### ISSUE TITLE
[Bug] Your package relies on older versions of dbt-utils, which means our project is stuck on an older version

### ISSUE THREAD

**Issue by rbrooks** [fivetran/dbt_hubspot#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Your package relies on older versions of dbt-utils, which means our project is stuck on an older version

### Expected behavior

We're allowed to upgrade to latest dbt-utils

### dbt Project configurations

n

### Package versions

```
packages:
  - package: fivetran/stripe
    version: [">=0.6.0", "<0.9.0"]
  - package: fivetran/hubspot
    version: [">=0.5.0", "<0.8.0"]
```

### What database are you using dbt with?

bigquery

### dbt Version

1.3.0

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.
